spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://postgres:5432/bookdb
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
          highlight.sql: true
  graphql:
    graphiql:
      enabled: true